spring:
    application:
        name: utils
    profiles:
        active: normal # default
    jpa:
        hibernate:
            ddl-auto: none # using liquibase to create schemas
        show-sql: true
logging:
    file: ./logs/database.log
    
---
spring:
    profiles: normal
    datasource: 
        url: jdbc:postgresql://eu-cdbr-west-01.cleardb.com/ heroku_88cc93af71af49e
        username: b3bddc1c4235ad
        password: 66cd63d8